### PR TITLE
idAttribute support + a fix for ignoring pre-defined id when adding to collection

### PR DESCRIPTION
**Pull request by costa**
This is basically a works-for-me change set — within limitations of the current implementation. However, I can improve it and add some tests if advised.

### CODE REVIEW

**Comment by davideast** [comment]
Thanks for the PR!

Can you provide some context and/or some example code? That would help me understand the importance of these changes.

**Comment by costa** [comment]
Okay, first off, `idAttribute` is a public feature of Backbone and should be supported. Then, I'm building a dual storage-transport app, which will "write" mainly to my Rails server (where I process the data in the comfort of my language of choice), and "read" mainly from Firebase (where all the changes are pushed). My supposedly straightforward approach to this is to use specially generated public keys with Firebase, hence `idAttribute: 'key'`.
I will hopefully write a blog post on this architecture if it all plays nicely in the end.

**Comment by davideast** [comment]
Sorry for the delay on this PR. I just gave it a firm review and it all looks good. Thank you so much for taking the time to help out!

**Comment by costa** [comment]
No worries, waiting for the new version.

**Pull request merged**
